### ISSUE TITLE
Create "Location Updates", "Score Updates" and "Event Updates" HTML Reports to Add To Or Replace Existing RSS Feeds

### ISSUE THREAD

**Issue by ericwagericwag** [pinballmap/pbm#1123]
[Medium Priority]
[Pretty Easy]

With the release of Firefox 64 in December 2018, Mozilla Firefox no longer supports RSS.  This means that users who access PinballMap via Firefox can no longer see the "Location RSS", "Score RSS" and "Event RSS" lists.  Microsoft Edge also doesn't display RSS feeds, except in a difficult to read markup format.

In researching this, I discovered that there are two types of articles about RSS on the internet, those titled "RSS is Dead" and those titled "Why Does Everybody Think RSS is Dead?".  Not sure which to believe, but at any rate, people should be able to see these useful PinballMap lists.

If you guys think it is no longer worth maintaining RSS, then please kill the existing RSS lists and replace them with simple HTML lists, or something.  If you guys think RSS technology still has value, then please create a new HTML list in addition to retaining the existing RSS.  Either way.  Whatever you think is best.

Thanks!

**Comment by RyanTG** [comment]
This is something we've been thinking about.

The RSS is still valuable, as it's used for twitter and facebook feeds.

In the app update, we're having a "recent nearby activity" feed (https://github.com/bpoore/pbm-react/issues/94 & https://github.com/scottwainstock/pbm/issues/1094). It displays all user submissions with a certain radius. Something like this could possibly be done for regions.

**Comment by RyanTG** [comment]
I think the solution to this would likely be the "recent activity" as mentioned above.

**Comment by RyanTG** [comment]
Made a "recent activity" page for each regional map. Example https://pinballmap.com/bayarea/activity
It shows the last 200 edits, sorted by date. https://github.com/pinballmap/pbm/commit/1c64315679d573bad94b6c8dc605d09932b4ad6f

Might tweak it some, but this is a working first pass.

I think this might have kind of been what you were asking for, Eric. Not sure if you use Pinball Map anymore. Next step is for us to create a "nearby recent activity" for the /map based on where the map is currently situated.
