### ISSUE TITLE
Sort Closest by proximity

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm#1137]
Right now when you do a “closest locations” search the results sort alphabetically. Would be nice to have a toggle - situated near the “10 locations in results” text - where you can switch between alpha and nearest.

**Comment by MikeMaven** [comment]
@RyanTG I'm going to start tackling this one tonight. If Ruby Geocoder isn't already being used in the code, I may add that to tackle this issue. It's lightweight and works great for sorting geocoded objects.

**Comment by RyanTG** [comment]
Sweet! We use ruby geocoder. When you do a closest locations search, it currently returns distance for each location.

**Comment by RyanTG** [comment]
Closing as stale. I can't figure it out.
