### ISSUE TITLE
Use effective_radius for the region's ifpa pull radius

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm#1214]
Some admins complain that the radius is too small. Others complain it's too big.

Right now it's baked in at 100 miles. https://github.com/scottwainstock/pbm/blob/master/lib/tasks/import_ifpa_tournaments.rake#L12

Could we instead use the effective_radius value?
https://github.com/scottwainstock/pbm/blob/dde9d9cc7fe6ccc4167540f7ebe2069b24f1dc06/app/controllers/api/v1/regions_controller.rb#L115

I'm not sure how to plug that into the task.

**Comment by scottwainstock** [comment]
@RyanTG Not sure how to handle this. The logic right now is "show me all locations within 100 miles of the location of this event" and then makes an event entry for the region all those locations are in.

There's a chicken/egg thing with the initial check. It starts from the event location and then tries to find all the regions around it. At that point it has no idea what regions are within X miles, so we pick a static value.

All I can think is to loop AGAIN and make sure the locations it found (which again have to be constrained to an initial large value) are within a smaller range?

The other option is to drop the initial check and have it loop through every location on the map and see if it's within EFFECTIVE_RADIUS miles. That seems like it's going to be really slow though.

**Comment by RyanTG** [comment]
Ah, gotcha. I didn't realize that's how it works.

I think your first idea sounds better than the second one (I agree that the second option seems like it would be slow, especially since this runs every day). So then we'd have to increase the initial value so it's greater than the greatest effective radius.
