### ISSUE TITLE
API endpoint for location history

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm#1223]
This is to fulfil https://github.com/scottwainstock/pbm/issues/1176 & https://github.com/bpoore/pbm-react/issues/255

On the app, and probably the website at some point, we want to show "location history." This would be a record of what machines have come and gone at a location. I don't think it's necessary show additional location history - like, confirmations and comments and location description edits (if you think I'm wrong here, let me know).

So we'd just have a list of machines adds and removals, sorted by most recent, and going back... as far as we can?

Scott says `Hitting up user submissions and filtering on a couple types.`

Let me know if you'd like additional information.

**Comment by bpoore** [comment]
Agreed a new endpoint is ideal so we can request the location history for a given location. Using the existing endpoint, we'd have to get `all` data within a given range and filter out all the locations other than the location of interest which if we open up the history beyond 30 days to get a more complete history, we'd be sending a **bunch** of unused data.
