### ISSUE TITLE
Refine the stale data message

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm#1300]
User feedback that essentially boils down to: the not updated in 2 years message could use improvement.

Ideas:
1) 2 years is too long; use a shorter length of time
2) Nudge the user to take action ("visit the place and update" etc)
3) Perhaps the messages can be scaled. 3 months, 1 year, 2 years...?
4) Some kind of icon denoting level of staleness.

**Comment by bpoore** [comment]
I think something along these lines is a great idea. I like that we added to the 2 year message, but would agree that other levels of warning would be nice or we could use a smaller length of time. 

As a user of the app myself, currently if I see the 2 year warning, I assume the chances of them having functional pinball is low and if the most recent update was prior to March 2020, I am also skeptical. When going about, I have been trying to check in on places and get stale locations updated... some sort of indication to encourage users to do the same would be great.
