### ISSUE TITLE
Migrate from the aws-sdk gem to the aws-s3 gem.

### ISSUE THREAD

**Issue by fiveNinePlusR** [pinballmap/pbm#1437]
It might be worthwhile to pare down the use of this gem and only pull in the aws gems that are strictly required for the app. the aws-sdk says it's a rather large gem and should only really be used when migrating from gem versions: 

> Alternatively, the aws-sdk gem contains every available AWS service gem. This gem is very large; it is recommended to use it only as a quick way to migrate from V2 or if you depend on many AWS services.

Might save on some CI time/storage fees on the server when deploying if we limit it to the s3 gem that, from what I can tell, is the only part of the aws suite that is in use.

**Comment by RyanTG** [comment]
https://github.com/pinballmap/pbm/pull/1439/commits/7e96064eac21932f2545b5a0ef12252417b42804

The initializer was creating an error with this new gem (even when "aws-sdk-s3" was in the loaded_specs). I removed the file completely in the next commit.

Tested on staging and seems fine. Can upload pics!
