### ISSUE TITLE
Create a GeoJSON version of the location within_bounding_box API endpoint

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm#1550]
This would be something for the app.

GeoJSON is a specific format for json: https://datatracker.ietf.org/doc/html/rfc7946

It seems like the way to do this is to construct a hash and then to_json it. This is not yet something I am familiar with doing.

If anyone else wants to do it, feel free.

**Comment by fiveNinePlusR** [comment]
Do you have a sample of the final data format you'd want it to be that's compatible with the mapbox shape layer?

**Comment by RyanTG** [comment]
I think like this. 

For reference, an example current within_bounding_box query: https://www.pinballmap.com/api/v1/locations/within_bounding_box.json?swlat=35.57053006119676;swlon=-82.84947699999975;nelat=37.08178259394671;nelon=-81.84947700000004;;no_details=1

An example of the current JSON of one location from that query:

```
{
  "locations": [
    {
      "id": 21211,
      "name": "The Bier Garden",
      "street": "46 Haywood St",
      "city": "Asheville",
      "state": "NC",
      "zip": "28801",
      "lat": "35.5959502",
      "lon": "-82.5550254",
      "updated_at": "2023-09-13T09:43:04.758-07:00",
      "location_type_id": 14,
      "operator_id": null,
      "machine_names_first": [
        "Jurassic Park (Pro) (Stern, 2019)"
      ],
      "machine_ids": [
        3167
      ],
      "num_machines": 1
    }
  ]
}
```

For GeoJSON, I think the above example should become this:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": 21211, //location id
      "geometry": {
        "type": "Point",
        "coordinates": [-74.00597, 40.71427], //lon, lat
      },
      "properties": {
        "icon": "example",
        "text": "example-icon-and-label",
        "name": "The Bier Garden",
        "street": "46 Haywood St",
        "city": "Asheville",
        "state": "NC",
        "zip": "28801",
        "lat": "35.5959502",
        "lon": "-82.5550254",
        "updated_at": "2023-09-13T09:43:04.758-07:00",
        "location_type_id": 14,
        "operator_id": null,
        "machine_names_first": [
          "Jurassic Park (Pro) (Stern, 2019)"
        ],
        "machine_ids": [
          3167
        ],
        "num_machines": 1
      },
    },
  ]
}
```

That's just an example with one location (and one machine at that location). If there are multiple locations, they would all be within the "features" key.

**Comment by RyanTG** [comment]
https://github.com/pinballmap/pbm/commit/8f45c3c0531ac86bade6600cce212f6ef69b2775
https://github.com/pinballmap/pbm/commit/d1d45397c41eb2be7de3ef1e89d8fe0a326c4bf6

However, we likely aren't going to use this in the app :sob:
