### ISSUE TITLE
Consider allowing machine comment to be deleted by author (and editable?)

### ISSUE THREAD

**Issue by RyanTG** [pinballmap/pbm#1576]
In the machine comments section, `- if mcx.user_id == current_user&.id` (or something) then show `edit` and `delete` text buttons for when the comment is made by that logged in user.

**Edit:** opens a textbox that contains the existing comment, and the user can edit the text. 

If the user _removes_ all the text, then I don't think we should show an empty comment. What is the easiest solution in this case? Maybe it would be to _not_ save the new condition if the value is empty. They should be choosing the delete option if that is their desire.

If a comment is revised, show an asterisk at the end of it...? Could that be determined by comparing the created_at vs the updated_at ?

User Submission: It seems like the original user submission should somehow be revised. But I don't think there's a connection (id) between the mcx and the user submission. But the user submission contains fields like "comment" "location_id" "user_id" so perhaps the mcx can be matched to the user_submission via those? Both the "submission" field and the "comment" field would need to be revised.

**Delete**: I don't know if this should be a "destroy" action, or if it should instead add some kind of "flag" to the mcx. Like, if flagged, then the comment becomes an italicized "comment was removed by author". I don't think it's a good idea to delete the comment and have a gap in the past comments.

Have a confirm popup.

User Submission: Not sure. Do we change the "comment" and "submission" fields to say "comment was removed by author" or do we remove the user submission entirely? It might be annoying for users to view "recent activity" and see activity about a comment removed. But maybe that would be ok, and better than completely removing the user submission (since it's nice to have a record of some sort).

We should make sure that paper_trail is active for machine comments and user submissions, so that we have a record of the edits.

**API**: needs to include the above functionality.

**Comment by scottwainstock** [comment]
https://github.com/pinballmap/pbm/pull/1577

**Comment by RyanTG** [comment]
I added some styles. And I added logic to show the "has been edited" asterisk. `- if mcx.updated_at != mcx.created_at` not sure if that's the best solution for that, though. Aren't there cases where updated_at and created_at could be different simply because the server is slow?

### Updating comment

If the user removes all the text, then I don't think we should show an empty comment. What is the easiest solution in this case? **Maybe it would be to not save the new condition if the value is empty**. They should be choosing the delete option if that is their desire.

### Deleting comment

I don't know if this should be a "destroy" action, or if it should instead add some kind of "flag" to the mcx. Like, if flagged, then the comment becomes an italicized "comment was removed by author". **I don't think it's a good idea to delete the comment and have a gap in the past comments.**

### User Submissions

**Updating comment:** It seems like the original user submission should somehow be revised. But I don't think there's a connection (id) between the mcx and the user submission. But the user submission contains fields like "comment" "location_id" "user_id" so perhaps the mcx can be matched to the user_submission via those? Both the "submission" field and the "comment" field would need to be revised.

**Deleting comment:** User Submission: Not sure. Do we change the "comment" and "submission" fields to say "comment was removed by author" or do we remove the user submission entirely? It might be annoying for users to view "recent activity" and see activity about a comment removed. But maybe that would be ok, and better than completely removing the user submission (since it's nice to have a record of some sort).

**Comment by RyanTG** [comment]
> Why don't you want gaps in past comments? I thought the whole point of this feature was to let people remove things that are no longer relevant.

The scenario I'm imagining is something like:

Older Comment = "The right flipper is broken"

Newer Comment (by another user) = "Issue still there."

If the Older Comment gets deleted, then we're left with "Issue still there." and nothing else. I was thinking that some kind of "comment has been deleted" would at least show us that _something_ was there before. But maybe I'm just over/wrongly thinking about it. I wasn't even thinking that it would include the username or anything of the deleted comment, but just a vague artifact that something used to exist there.

Reddit does something like that: 
![image](https://github.com/pinballmap/pbm/assets/632682/6e56fc12-146a-40f0-bdf5-d8c43809e02a)

But you're probably right, and, like you said, tricky.

> Why? Isn't this a net-new action?

The scenario I was thinking of was fixing a typo (or some other mistake) and having the user submission show the corrected text. And I thought a new submission might end producing a spammy effect.

The User Submission is a customer-facing artifact in some contexts. On the website, you can view "Location Activity" to see a log of the most recent user submissions. And on the app, there's both a "Recent Activity" feed showing all nearby User Submissions, as well as a location-specific feed. That's why I thought users might find it strange for there to be a mismatch between those feeds and the actual comment.

But maybe this is one of those "release as is and see if people give feedback" things.

**Comment by scottwainstock** [comment]
Let's discuss this on the podcast.

**Comment by scottwainstock** [comment]
New PR for this issue: https://github.com/pinballmap/pbm/pull/1578

Extra condition handling for comments was added here: https://github.com/pinballmap/pbm/pull/1578/commits/d783820256686cb45d3cb44264138d6a4003896c

**Comment by RyanTG** [comment]
Deployed!
