### ISSUE TITLE
Mark a machine add/remove/update as "Pending"?

### ISSUE THREAD

**Issue by nmschulte** [pinballmap/pbm#1579]
Is there any interest to support a "pending" machine change?  Like, "new machine Zzz will arrive on mm/dd," or "machine Zzz will be removed on mm/dd"?

**Comment by RyanTG** [comment]
Hi. Thanks for the idea. We take it the motivation is so operators can generate interest ahead of time by noting which machines are coming/going soon. 

So far we don't have much interest in this.

Some thoughts:

- It would introduce a new data point with a high risk of not being updated. For example, a user setting a machine to "coming soon" or "leaving soon" and then never coming back and changing it to "here" or "gone."
- Creates complications with searching and presenting results. I think we'd have to let users filter out the coming soon ones if they don't want to see those. Seems like a hefty amount of coding work and more interfaces for users to learn.
- In general, we like to live in the here and now on the map. And people want to use the site to find machines to play. Also note that people don't really read things carefully, and a "coming soon" would very likely get mistaken for a "here" machine no matter what flags we put around it (plus, the machine might be there, but just not updated as such on the map).
