### ISSUE TITLE
speed up test suite

### ISSUE THREAD

**Issue by scottwainstock** [pinballmap/pbm#497]
It's getting slower (~3.5 minutes). Definitely could remove some "sleep"s. Probably there are other things too.

**Comment by scottwainstock** [comment]
https://github.com/grosser/parallel_tests

**Comment by RyanTG** [comment]
https://planetscale.com/blog/how-our-rails-test-suite-runs-in-1-minute-on-buildkite

**Comment by RyanTG** [comment]
In the last couple weeks I upgraded rails from 5.x to 6.x and ruby from 2.x to 3.x (and lots of gems). And overall test time went from like 8 minutes to 3. Though I also got a new laptop, so maybe that's the reason. Anyway, cool!

````
Finished in 3 minutes 14.9 seconds (files took 1.59 seconds to load)
488 examples, 0 failures
````
